In [1]:
import numpy as np

In [18]:
# create nparray from list
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype, arr.shape) # dtype shows under kya store hai , shape -> dimension

arr2 = np.array([1,2,3,4,'prime'])
print(arr2, type(arr2), arr2.dtype, arr2.shape) # U21 -> unified string , shape -> dimension for 1d array it show length of array

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' 'prime'] <class 'numpy.ndarray'> <U21 (5,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
