In [1]:
import numpy as np

In [19]:
# create np array using built in function
arr0 = np.zeros((2,3)) # by default create a float data type  - zeros(pass the dimension)
print(arr0)
arr0 = np.zeros((2,3), dtype="int64")
print(arr0, arr0.shape)

arr1 = np.ones((5,)) # pass the dimension
print(arr1)

arr2 = np.full((3,4), 100) #prefill with val
print(arr2)

arr3 = np.eye(3, dtype="int64") #Identity Matrix
print(arr3)

arr4 = np.arange(0,10,2) 
print(arr4)

arr5 = np.linspace(1,100,4) #evenly space array 
print(arr5)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[0 2 4 6 8]
[  1.  34.  67. 100.]


In [24]:
# Properties
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr.shape) # dimension -> (m*n)
print(arr.size) # tot_element = 9
print(arr.dtype) 
print(arr.ndim) #dimensions -> 1d ,2d, 3d

# type casting in existing array
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64
