In [1]:
import numpy as np

In [5]:
# Images storing 
# 1. B&W images store in 2D matrix (0 -> white and 255 -> black and rest number shows the depth)
# in 2d matrix we store the number

# 2. color image we store the RGB(red,blue,green)
# so we create a three matrix for R for Blue and for Green

# 1D -> 1Axis (axis 0)
# 2D -> 2Axes (axis 0 -> row -> vertically (har row ke 0's index pe operation perform and 1's index and so on)
#               axis 2 -> column -> horizontal (har column ke 0's index pe operation perform and 1's index and so on)
# or remember axis = 0 -> vertical and axis = 1 -> horizontal
# 3D -> 3Axes (axis 0 -> depth/layer , axis 1 -> row , axis 2 -> column)


# 2D array
arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D)
print(np.sum(arr2D))

# axis
sum_of_columns = np.sum(arr2D, axis = 0) # axis = 0 -> vertical
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1) #axis = 1 -> horizontal
print(sum_of_rows)

# Slicing in 2D array
print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [21]:
#3D Array
arr3D = np.array([ [ [1,2,], [3,4], [5,6] ],[ [7,8], [9,10], [11,12] ] ])  # 2 * 3 * 2  => 2D array me 3rows*2Columns
print(arr3D, arr3D.shape)

# Indexing
print("\nIndexing")
print(arr3D[0, 1, 1]) # select the layer 1st layer in this select the row and column [0,1,1]

# slicing
print("\nslicing")
# get the first row from both layers
print(arr3D[: , 0 , :])  #[both layer(:) , first row(:), all the column(:)]

# get the first column from both layers
print(arr3D[:, :, 0]) # [both layer, all the rows, first column ]

# manipulation
print("\nManipulation")
arr3D[:, 0, :] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)

Indexing
4

slicing
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]

Manipulation
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]
