In [1]:
import numpy as np

In [4]:
# Vectorization
arr = np.array([1,2,3,4,5])
arr1 = np.array([6.,7,8,9,10])

print(arr ** 2)
print(arr + 10)
print(arr + arr1)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7.  9. 11. 13. 15.]


In [6]:
# BroadCasting

arr = np.array([1,2,3,4,5])
arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr + arr1)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
